service: basic-serverless-lambda

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: ap-south-a

functions:
  hello:
    handler: src/handler.generateRandomNumber
    timeout: 60 # seconds
    memorySize: 128 # mb
